tests

diff --git a/.github/workflows/playwright.yml b/.github/workflows/playwright.yml
--- a/.github/workflows/playwright.yml
+++ b/.github/workflows/playwright.yml
@@ -24,8 +24,15 @@ jobs:
         npm run tests
         # Capture the exit code of the last command
         exit_code=$?
-        # Set the output variable with the exit code
-        echo "::set-output name=exit_code::$exit_code"
+        # Save the exit code to an environment file
+        echo "PLAYWRIGHT_TESTS_EXIT_CODE=$exit_code" > playwright_tests_env
+    - name: Check Playwright test results
+      run: |
+        exit_code=$(cat playwright_tests_env | grep 'PLAYWRIGHT_TESTS_EXIT_CODE' | cut -d'=' -f2)
+        if [ $exit_code -ne 0 ]; then
+          echo "Playwright tests failed with exit code $exit_code"
+          exit 1
+        fi
     - uses: actions/upload-artifact@v3
       if: always()
       with:
